[tool.poetry]
name = "recommender-system-study"
version = "0.1.0"
description = ""
authors = ["Kang-bh <kabyho3513@gmail.com>"]
readme = "README.md"
[tool.poetry.dependencies]
python = "^3.10.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"